project_id = "ciwnnlnbptyjoppthxhy"

[functions.generate-message]
verify_jwt = false

[functions.sync-activecampaign]
verify_jwt = false

[functions.n8n-new-leads]
verify_jwt = false

[functions.n8n-mark-contacted]
verify_jwt = false

[functions.receive-lead]
verify_jwt = false
